######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 13 16:31:09 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += core gui network

# Input
HEADERS += addressMsg.h frmmain.h myclientsocket.h myhelper.h mytcpserver.h
SOURCES += frmmain.cpp main.cpp myclientsocket.cpp mytcpserver.cpp
