######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 16 22:23:07 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += board.h
SOURCES += board.cpp main.cpp
