######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 15 22:29:08 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
