######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 16 22:12:28 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
