######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 20 00:28:32 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += win1.h
SOURCES += main.cpp win1.cpp
