######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 14 22:38:00 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += servers_1.h
FORMS += servers_1.ui
SOURCES += main.cpp servers_1.cpp
