######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 14 22:36:58 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += dialog.h dialogrec.h feiq_3.h
FORMS += dialog.ui dialogrec.ui feiq_3.ui
SOURCES += dialog.cpp dialogrec.cpp feiq_3.cpp main.cpp
