######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 13 20:20:03 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += core gui network

# Input
HEADERS += frmmain.h myhelper.h
SOURCES += frmmain.cpp main.cpp
