######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 13 11:15:57 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
SOURCES += main.cpp mywidget.cpp
