######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 6 20:02:16 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += background.cpp
