######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 15 12:44:25 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
SOURCES += main.cpp
