######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 16 21:27:28 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp
RESOURCES += widget.qrc
