######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 21 00:35:01 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += win1.h
SOURCES += main.cpp win1.cpp
