######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 16 19:35:11 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += des.ui
SOURCES += main.cpp
